<?php $script= $this->tag->javascriptInclude('public/ckeditor/ckeditor.js'); ?>
<form action="<?php echo $this->url->get('admin/page/create'); ?>" method="post" class="form-horizontal">
<div class="row-fluid">
	<div class="col-sm-offset-11 col-sm-1">
		<button type="submit" class="btn btn-default form-control">Save</button>
	</div>
</div>
<div class="row-fluid">
	<div class="col-md-2 col-sm-6"><!-- Left side of the form -->
		<div class="form-group">
		<label>Menu List</label>
			<div class="list-group col-md-10">
				<li class="list-group-item"><a href="javascript:void(0);" id="home">Home</a></li>
				<li class="list-group-item"><a href="javascript:void(0);" id="about">About</a></li>
				<li class="list-group-item"><a href="javascript:void(0);" id="contact">ContactUs</a></li>
			</div>
		</div>
	</div><!-- end Left side form -->
	<div class="col-md-9 col-sm-12"><!-- Middle of the form -->
		<div class="form-group">
		<label>Home</label>
			<textarea class="col-md-9 col-sm-10 form-control" >hello
				hello
			</textarea>
		</div>
		<div class="form-group" style="display:none" id='form-contact'>
		<label>Contact:</label> <span class="pull-right remove"><i class="glyphicon glyphicon-remove"></i></span>
			<textarea class="col-md-9 col-sm-10 form-control" >hello
				hello
			</textarea>
		</div>
		<div class="form-group" style="display:none" id='form-about'>
		<label>About:</label><span class="pull-right remove"><i class="glyphicon glyphicon-remove"></i></span>
			<textarea class="col-md-9 col-sm-10 form-control" >hello
				hello
			</textarea>
		</div>
	</div>
</div>
<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken(); ?>" />
</form>

<?php 
if($id)
{
		$url=$this->url->get('admin/page/PageById/'.$id);
		$scripts=
		"$(function(){
			$.get('$url')
			.success(function(data){
				var data=$.parseJSON(data);
				if(data.content)
				{

				}
			});
			$('#contact').on('click',function(){
				$('#form-contact').show();
			});
			$('#about').on('click',function(){
				$('#form-about').show();
			})
			$('.remove').on('click',function(){
				
			});
				

		})";
}
 ?>
	

