<div class="list-group">
            <a href="<?php echo $this->url->get('admin/channel/create'); ?>" class="list-group-item">AddChannels</a>
            <a href="<?php echo $this->url->get('admin/channel/view') ?>" class="list-group-item">ViewChannel</a>
            <a href="<?php echo $this->url->get('admin/slugpage/create') ?>" class="list-group-item">
            Create SlugPage</a>
</div>
