<?php $this->flash->output(); ?>

<div id="no-more-tables" ng-app="channel">
<table class="col-md-12 table-bordered table-striped table-condensed cf"> 
	<thead class="cf">
		<tr>
			<th>Sno</th>
			<th>Name</th>
			<th>UserName</th>
			<th>Email</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	
		<tr>
			<td data-title="Sno"><?php echo $i;$i++; ?></td>
			<td data-title="Name"><?php echo $user->user->firstName; ?></td>
			<td data-title="UserName"><?php echo $user->user->userName; ?></td>
			<td data-title="Email"><?php echo $user->user->email; ?></td>
			<td data-title="Action">
				<div class="btn-group">
					<button  class="btn btn-primary btn-md dropdown-toggle" data-toggle="dropdown">Action<span class="caret"></span></button>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Edit</a></li>
						<li><a href="<?php echo $this->url->get('channel/user/delete/'.$user->id); ?>">Delete</a></li>
					</ul>
				</div>
				
			</td>
		</tr>
	
	</tbody>
</table>
